include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Style rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: true
    
    # Effective Dart - Style
    prefer_single_quotes: true
    always_declare_return_types: true
    avoid_print: true
    avoid_relative_lib_imports: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    
    # Effective Dart - Usage
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    prefer_asserts_in_initializer_lists: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    
    # Effective Dart - Design
    avoid_void_async: true
    prefer_bool_in_asserts: true
    
    # Additional best practices
    camel_case_types: true
    library_names: true
    non_constant_identifier_names: true
    prefer_is_not_operator: true
    sort_child_properties_last: true
    use_build_context_synchronously: true
    
analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
  errors:
    invalid_annotation_target: ignore
  
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
